Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import sympy as sym


sign = sym.Function("sign")
f1 = sym.symbols("\hat{f}_1(x)")
f2 = sym.symbols("\hat{f}_2(x)")
f3 = sym.symbols("\hat{f}_3(x)")
f =  round(model_weight1, 3) * f1 + round(model_weight2, 3) * f2 + round(model_weight3, 3) * f3
glue("example_equation", sign(f), display=False)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[12], line 1[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01msympy[39;00m [38;5;28;01mas[39;00m [38;5;21;01msym[39;00m
[1;32m      4[0m sign [38;5;241m=[39m sym[38;5;241m.[39mFunction([38;5;124m"[39m[38;5;124msign[39m[38;5;124m"[39m)
[1;32m      5[0m f1 [38;5;241m=[39m sym[38;5;241m.[39msymbols([38;5;124m"[39m[38;5;124m\[39m[38;5;124mhat[39m[38;5;132;01m{f}[39;00m[38;5;124m_1(x)[39m[38;5;124m"[39m)

[0;31mModuleNotFoundError[0m: No module named 'sympy'

